version: '3'

services:
  college_api: 
    build:
      context: ./college-api/
      dockerfile: Dockerfile
    ports: 
      - "8000:8000"
    depends_on: 
      - postgres_db

  embeddings_extraction:
    build: 
      context: ./embeddings-extraction/
      dockerfile: Dockerfile
    ports:
      - "8001:8001"
    depends_on: 
      - rabbitmq

  assistance_tracker:
    build: 
      context: ./assistance-tracker/
      dockerfile: Dockerfile
    depends_on:
      - rabbitmq
  
  postgres_db:
    image: postgres:latest
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: college_api  # Corregido el nombre de la variable
    ports:
      - "5432:5432"
    volumes:
      - ./postgres_data:/var/lib/postgresql/data

  rabbitmq:
    image: rabbitmq:latest
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: password
    volumes:
      - ./rabbitmq_data:/var/lib/rabbitmq
